### ISSUE TITLE
Filter 

### ISSUE THREAD

**Issue by joshuajhun** [jbevis/Get-Out-There#50]
- Decide if you are going to filter on the react end or the redux 
   - pros for react is that when there is nothing you can just render all the things.

**Comment by jbevis** [comment]
Update to issue:
Based on feedback from pairing with Meeka, going with Redux, but able to remove filter action and reducer. if no difficulties match, returning new message with link back to all trails. Will hope to break all these out into new components

**Comment by jbevis** [comment]
filter has been broken out into its own component, filter logic is being handled by displayreducer now.
